name: Update the avialable versions table in README.md
on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update the avialable versions table in README.md
        shell: bash
        run: |
          sudo apt update && sudo apt -y install python3 python3-pip
          pip3 install natsort
          ./test/generate_table.py
